AWSTemplateFormatVersion: "2010-09-09"

Description: 'IAM Cloud'

Parameters:
    Password:
        Type: String
        Description: "One time password for IAM users"
        NoEcho: true

Resources:
    OneTimePassword:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: 'OneTimePassword'
            Description: 'One time password for IAM users'
            SecretString: !Ref Password

    MyMainUser1:
      Type: AWS::IAM::User
      Properties:
        UserName: 'ebrayceUser1'
        Password: !Ref Password

    MyMainUser2:
          Type: AWS::IAM::User
          Properties:
            UserName: 'ebrayceUser2'
            Password: !Ref Password
            Groups:
              - !Ref S3UserGroup

    MyMainUser3:
         Type: AWS::IAM::User
         Properties:
           UserName: 'ebrayceUser3'
           Password: !Ref Password

    S3UserGroup:
      Type: AWS::IAM::Group
      Properties:
        GroupName: 's3-users'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

