AWSTemplateFormatVersion: "2010-09-09"

Description: 'IAM Cloud'

Parameters:
    Password:
        Type: String
        Description: "One time password for IAM users"
        NoEcho: true

Resources:
    OneTimePassword:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: 'OneTimePassword'
            Description: 'One time password for IAM users'
            SecretString: !Ref Password

    MyMainUser1:
      Type: AWS::IAM::User
      Properties:
        UserName: 'ec2-user1'
        LoginProfile:
          Password: !Ref Password
          PasswordResetRequired: true
        Groups:
          - !Ref EC2UserGroup

    MyMainUser2:
          Type: AWS::IAM::User
          Properties:
            UserName: 'ec2-user2'
            LoginProfile:
              Password: !Ref Password
              PasswordResetRequired: true
            Groups:
              - !Ref EC2UserGroup

            Policies:
              - PolicyName: 'PreventEC2Creation'
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Deny
                        Action: "ec2:RunInstances"
                        Resource: '*'

    MyMainUser3:
         Type: AWS::IAM::User
         Properties:
           UserName: 's3-user'
           LoginProfile:
             Password: !Ref Password
             PasswordResetRequired: true
           Groups:
             - !Ref S3UserGroup

    S3UserGroup:
      Type: AWS::IAM::Group
      Properties:
        GroupName: 's3-users'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
          - arn:aws:iam::aws:policy/IAMUserChangePassword
          - arn:aws:iam::aws:policy/ReadOnlyAccess

    EC2UserGroup:
      Type: AWS::IAM::Group
      Properties:
        GroupName: 'ec2-users'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEC2FullAccess

Outputs:
  ConsoleLoginURL:
    Description: "The URL for your users to log into the AWS Console"
    Value: !Sub "https://${AWS::AccountId}.signin.aws.amazon.com/console"

